### ISSUE TITLE
Git function creation fails due to missing GitRepository CR

### ISSUE THREAD

**Issue by m00g3n** [kyma-incubator/hydroform#135]
**Description**

Function creation fails due to missing GitRepository CR.

**Expected result**

Function should be created.

**Actual result**

```yaml
Name:         nodejsgit
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  serverless.kyma-project.io/v1alpha1
Kind:         Function
Metadata:
  Creation Timestamp:  2020-11-12T09:13:28Z
  Generation:          1
  Resource Version:    2816854
  Self Link:           /apis/serverless.kyma-project.io/v1alpha1/namespaces/default/functions/nodejsgit
  UID:                 3c401911-53f5-4b79-a574-e46e84e24fbd
Spec:
  Base Dir:  /
  Build Resources:
    Limits:
      Cpu:     700m
      Memory:  700Mi
    Requests:
      Cpu:       200m
      Memory:    200Mi
  Max Replicas:  1
  Min Replicas:  1
  Reference:     master
  Resources:
    Limits:
      Cpu:     100m
      Memory:  128Mi
    Requests:
      Cpu:     50m
      Memory:  64Mi
  Runtime:     nodejs12
  Source:      nodejsgit
  Type:        git
Status:
  Conditions:
    Last Transition Time:  2020-11-12T09:13:28Z
    Message:               Sources update failed: GitRepository.serverless.kyma-project.io "nodejsgit" not found
    Reason:                SourceUpdateFailed
    Status:                False
    Type:                  ConfigurationReady
  Runtime:                 nodejs12
  Source:                  nodejsgit
Events:                    <none>

```

**Steps to reproduce**

- Create `git` type function e.g

```bash
kyma init function --name=nodejsgit --url=https://github.com/m00g3n/public-gitops.git
```

- Apply function using function CLI

```bash
kyma apply function
```

**Troubleshooting**
